global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
          - localhost:9090
  - job_name: cpu-stats-exporter
    static_configs:
      - targets:
          - 192.168.0.101:8080
          - 192.168.0.102:8080
          - 192.168.0.53:8080
          - 192.168.0.103:8080
          - 192.168.0.105:8080